### ISSUE TITLE
Einreichung zu Publikation

### ISSUE THREAD

**Issue by LukasCBossert** [LukasCBossert/DTK-TeX-Python#2]
Schaffen wir es bis morgen den Artikel noch fertig zu bekommen – oder dann eher für die Ausgabe 3/2016 @UweZiegenhagen ?
Gibt es Neuigkeiten zum Python-Code?

**Comment by LukasCBossert** [comment]
bei https://github.com/LukasCBossert/DTK-TeX-Python/blob/master/dtk-catalogueentry.tex#L252 : Ist die "2" am Ende des Labels bewusst gesetzt, @UweZiegenhagen ?

**Comment by UweZiegenhagen** [comment]
Nin, muss verrutscht sein. Nehm ich raus.

Uwe

2016-07-14 23:56 GMT+02:00 Lukas C. Bossert <notifications@github.com>:

> bei
> https://github.com/LukasCBossert/DTK-TeX-Python/blob/master/dtk-catalogueentry.tex#L252
> : Ist die "2" am Ende des Labels bewusst gesetzt, @UweZiegenhagen
> <https://github.com/UweZiegenhagen> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/LukasCBossert/DTK-TeX-Python/issues/2#issuecomment-232804446>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABLsHMTuc7NjQmy5n8s2l5_Tz5RHog_fks5qVrCDgaJpZM4IHHzZ>
> .
>



-- 
Dr. Uwe Ziegenhagen
<http://www.uweziegenhagen.de>
